substitutions:
  name: "hcpbridge"
  friendly_name: "HCPBridge"
  connection_state: "HCP2 Bus"
  relay_name: "External Relay"
  light: "Light"
  btn_vent: "Vent"
  btn_half: "Open Half"
  btn_impulse: "Impulse"
  sen_txt: "State"
  sw_vent: "Ventilation"
  sw_half: "Half-Open"
  sen_pos: "Position"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "HCPBridge for Hörmann Supramatic 4"
  min_version: 2026.5.1
  libraries:
    - emelianov/modbus-esp8266
  platformio_options:
    lib_compat_mode: "off"

external_components:
   - source:
      type: local
      path: components

esp32:
  variant: esp32s3
  cpu_frequency: 240MHZ
  flash_size: 4MB
  framework:
    type: esp-idf
    version: recommended
    components:
      - espressif/arduino-esp32==3.3.10

logger:
  level: WARN
  hardware_uart: UART0
  # Important: Disable UART1 logging to avoid hardware errors on main UART0
  #baud_rate: 0

api:
  encryption:
    key: !secret api_key
  reboot_timeout: 0s
  services:
    - service: go_to_open
      then:
        - lambda: |-
            id(garagedoor_cover).on_go_to_open();
    - service: go_to_close
      then:
        - lambda: |-
            id(garagedoor_cover).on_go_to_close();
    - service: go_to_half
      then:
        - lambda: |-
            id(garagedoor_cover).on_go_to_half();
    - service: go_to_vent
      then:
        - lambda: |-
            id(garagedoor_cover).on_go_to_vent();
    - service: toggle
      then:
        - cover.toggle: garagedoor_cover

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  reboot_timeout: 0s
  enable_rrm: True
  use_psram: True

psram:
  mode: quad
  speed: 80MHz
  ignore_not_found: False

network:
    enable_ipv6: True

hcpbridge:
  id: hcpbridge_main
  rx_pin: 18 # optional, default=18
  tx_pin: 17 # optional, default=17
  slave_id: 69
  #rts_pin : 1 # optional RTS pin to use if hardware automatic control flow is not available.

debug:
  update_interval: 30s

cover:
  - platform: hcpbridge
    name: "Garage Door"
    device_class: garage
    id: garagedoor_cover

binary_sensor:
  - platform: hcpbridge
    is_connected:
      name: "${connection_state}"
      id: sensor_connected
    relay_state:
      name: "${relay_name}"
      id: sensor_relay

output:
  - platform: hcpbridge
    id: output_light

light:
  - platform: hcpbridge
    id: gd_light
    output: output_light
    name: "${light}"

button:
  - platform: hcpbridge
    vent_button:
      id: button_vent
      name: "${btn_vent}"
    impulse_button:
      id: button_impulse
      name: "${btn_impulse}"
    half_button:
      id: button_half
      name: "${btn_half}"
  - platform: restart
    name: "Restart"

text_sensor:
  - platform: hcpbridge
    id: sensor_templ_state
    name: "${sen_txt}"
  - platform: debug
    reset_reason:
      name: "Reset Reason"

switch:
  - platform: hcpbridge
    vent_switch:
      id: switch_vent
      name: "${sw_vent}"
      restore_mode: disabled
    half_switch:
      id: switch_half
      name: "${sw_half}"
      restore_mode: disabled

sensor:
  - platform: hcpbridge
    id: sensor_position
    name: "${sen_pos}"
  - platform: debug
    free:
      name: "Heap Free"
